### PR TITLE
Add support for upsert update option

### PR DESCRIPTION
**Pull request by YurySolovyov**
Adds support for `upsert` update option.
Ref. #3

### CODE REVIEW

**Comment by YurySolovyov** [comment]
@nevf ping, it would be great if you can take a look at this, or even try it out.
I didn't worked on WriteResult though.

**Comment by nevf** [comment]
@YuriSolovyov Thanks, I'll try it today and get back to you.

**Comment by nevf** [comment]
@YuriSolovyov I'm getting an exception at line: 529 `return new Dexie.Promise(..`as follows:

```
Potentially unhandled rejection [2] ReferenceError: Dexie is not defined
    at createUpsertModifier (http://neville-red/db/Dexie.mongoify.js:529:20)
    at performCollectionUpdate (http://neville-red/db/Dexie.mongoify.js:717:20)
    at WriteableTable.update (http://neville-red/db/Dexie.mongoify.js:759:24)
    at http://neville-red/db/browser_db.js:103:33
```

I'm using Dexie as an amd module.

**Comment by nevf** [comment]
@YuriSolovyov Thanks for the quick update. `upsert` is working nicely. Looking forward to `resolve( WriteResult )` etc. when you have time.

**Pull request merged**
